spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bob
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${SECRET_KEY}
  jackson:
    serialization:
      fail-on-empty-beans: false
  elasticsearch:
    username: ${ELASTIC_NAME}
    password: ${ELASTIC_SECRET}
    hostname: ${ELASTIC_HOSTNAME}
    port: ${ELASTIC_PORT}
  main:
    allow-bean-definition-overriding: true

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      path: ${BUCKET_PATH}
    stack.auto: false
    credentials:
      accessKey: ${BUCKET_ACCESS_KEY}
      secretKey: ${BUCKET_SECRET_KEY}
    region:
      static: ap-southeast-2

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

scheduler:
  scrap:
    10000Recipe: "0 0 2 1 * *"

recipe:
  source:
    url: "http://localhost:8080/recipe/"
