spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bob
    username: root
    password: 1111
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true